// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
#include "plugin.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `fusion:compositor/general`

__attribute__((__import_module__("fusion:compositor/general"), __import_name__("debug")))
extern void __wasm_import_fusion_compositor_general_debug(uint8_t *, size_t);

__attribute__((__import_module__("fusion:compositor/general"), __import_name__("info")))
extern void __wasm_import_fusion_compositor_general_info(uint8_t *, size_t);

__attribute__((__import_module__("fusion:compositor/general"), __import_name__("warn")))
extern void __wasm_import_fusion_compositor_general_warn(uint8_t *, size_t);

__attribute__((__import_module__("fusion:compositor/general"), __import_name__("error")))
extern void __wasm_import_fusion_compositor_general_error(uint8_t *, size_t);

__attribute__((__import_module__("fusion:compositor/general"), __import_name__("config-get")))
extern void __wasm_import_fusion_compositor_general_config_get(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("fusion:compositor/general"), __import_name__("config-delete")))
extern void __wasm_import_fusion_compositor_general_config_delete(uint8_t *, size_t);

// Exported Functions from `plugin`







// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void plugin_string_set(plugin_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void plugin_string_dup(plugin_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_dup_n(plugin_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_free(plugin_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void fusion_compositor_general_debug(plugin_string_t *message) {
  __wasm_import_fusion_compositor_general_debug((uint8_t *) (*message).ptr, (*message).len);
}

void fusion_compositor_general_info(plugin_string_t *message) {
  __wasm_import_fusion_compositor_general_info((uint8_t *) (*message).ptr, (*message).len);
}

void fusion_compositor_general_warn(plugin_string_t *message) {
  __wasm_import_fusion_compositor_general_warn((uint8_t *) (*message).ptr, (*message).len);
}

void fusion_compositor_general_error(plugin_string_t *message) {
  __wasm_import_fusion_compositor_general_error((uint8_t *) (*message).ptr, (*message).len);
}

void fusion_compositor_general_config_get(plugin_string_t *path, plugin_string_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_fusion_compositor_general_config_get((uint8_t *) (*path).ptr, (*path).len, ptr);
  *ret = (plugin_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

void fusion_compositor_general_config_delete(plugin_string_t *path) {
  __wasm_import_fusion_compositor_general_config_delete((uint8_t *) (*path).ptr, (*path).len);
}

__attribute__((__export_name__("init")))
void __wasm_export_exports_plugin_init(void) {
  exports_plugin_init();
}

__attribute__((__export_name__("tick")))
void __wasm_export_exports_plugin_tick(void) {
  exports_plugin_tick();
}

__attribute__((__export_name__("stop")))
void __wasm_export_exports_plugin_stop(void) {
  exports_plugin_stop();
}

__attribute__((__export_name__("heap-allocated")))
int64_t __wasm_export_exports_plugin_heap_allocated(void) {
  uint64_t ret = exports_plugin_heap_allocated();
  return (int64_t) (ret);
}

__attribute__((__export_name__("heap-capacity")))
int64_t __wasm_export_exports_plugin_heap_capacity(void) {
  uint64_t ret = exports_plugin_heap_capacity();
  return (int64_t) (ret);
}

__attribute__((__export_name__("heap-free")))
int64_t __wasm_export_exports_plugin_heap_free(void) {
  uint64_t ret = exports_plugin_heap_free();
  return (int64_t) (ret);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_plugin(void);
__attribute__((used))
void __component_type_object_force_link_plugin_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_plugin();
}
