package fusion:compositor;

interface window-manager {
    record window-id {
        inner: u64,
    }

    get-elements: func() -> list<window-id>;
    set-window-size: func(window: window-id, width: u32, height: u32);
    set-window-pos: func(window: window-id, x: u32, y: u32);

    get-output-size: func() -> tuple<u32, u32>;
    //send-configure: func(window: window-id);

}
