package fusion:compositor;

world compositor {
    export tick: func();
    export stop: func();

    export heap-allocated: func() -> u64;
    export heap-capacity: func() -> u64;
    export heap-free: func() -> u64;

    import window-manager;
    export rearrange-windows: func();
}
