package fusion:compositor;

interface types {
    record window-id {
        inner: u64,
    }
}

interface wm-imports {
    use types.{window-id};

    get-elements: func() -> list<window-id>;
    set-window-size: func(window: window-id, width: u32, height: u32);
    set-window-pos: func(window: window-id, x: u32, y: u32);

    get-output-size: func() -> tuple<u32, u32>;
    send-configure: func(window: window-id);
}

interface wm-exports {
    use types.{window-id};

    new-toplevel: func(window: window-id);
    toplevel-destroyed: func(window: window-id);
    rearrange-windows: func();
}
